[filters]

    [filters.uid]
    csv_col = "uid"
    type = "filter"
    text = "Filter by identifier"

    [filters.name]
    csv_col = "name"
    type = "fuzzy"
    text = "Fuzzy search by full name"
    threshold = 0.4

    [filters.gender]
    csv_col = "gender"
    type = "checkbox"
    text = "Filter by gender" # set to "" if no text desired
    options = ["m", "f"] # ensure these correspond to values in csv

    [filters.occupation]
    csv_col = "occupation"
    type = "fuzzy"
    text = "Fuzzy search by occupation"
    threshold = 0.4

[table]

    [table.col0]
    type = "image"
    width = 0.1
    img_max_height = 150
    img_max_width = 100
    header_text = "Photograph"
    csv_col = "image" # this col of csv should contain relative path of images

    [table.col1]
    type = "text"
    width = 0.1
    header_text = "Identifier"
    csv_col = "uid"

    [table.col2]
    type = "text"
    width = 0.3
    header_text = "Full Name"
    csv_col = "name"

    [table.col3]
    type = "text"
    width = 0.1
    header_text = "Gender"
    csv_col = "gender"

    [table.col4]
    type = "text"
    width = 0.1
    header_text = "Age"
    csv_col = "age"

    [table.col5]
    type = "text"
    width = 0.3
    header_text = "Occupation"
    csv_col = "occupation"
